### ISSUE TITLE
Managing DAGs and plugins updates automatically

### ISSUE THREAD

**Issue by jnogol** [idealista/airflow-role#14]
A colleague asked for an automatic way to import DAGs and plugins from a Git repo every 5 minutes via cron job. Several changes were made to do so:

- `defaults/main.yml`: 
  - Added git in `airflow_required_libs`
  - Added `dags_dependencies` dictionary. Is meant to be the Python dependencies demanded by the DAGs.
    If empty, should be left with `{}`. If set, should follow the example:
    ```yaml
    scrapinghub:
      version: 2.0.1
    ```
  - Added `dags_repository` dictionary. Is meant to be the Git repositories containing DAGs or plugins that we want to check.
    If empty, should be left with `{}`. If set, should follow the example:
    ```yaml
    dags:
      src: https://github.com/apache/incubator-airflow/
      repo_subfolder: airflow/example_dags
      host_subfolder: "{{ airflow_dags_folder }}"
    ```
- `tasks/install.yml`:
  - Added task to install DAGs dependencies and restart Airflow stack if there are any new packages installed.
- `tasks/config.yml`:
  - Added task to create the cron jobs to check the repositories every 5 minutes.
