### ISSUE TITLE
Airflow 1.10 won't work when using LDAP

### ISSUE THREAD

**Issue by jnogol** [idealista/airflow-role#47]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Checked that your issue isn't already filled: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aidealista
    * Checked that there is not already provided the described functionality

### Description

When LDAP is enabled in Airflow, it crashes with the same output as this [question in Stack Overflow](https://stackoverflow.com/questions/51710114/airflow-critical-cannot-import-authentication-module-airflow-contrib-auth-ba). The problem is with the pip package `pyasn1`, that happens to be in a outdated version. Upgrading it solves the problem.

### Steps to Reproduce

1. Set in a vars file
``` yml
airflow_version: 1.10.0
airflow_webserver_authenticate: True
airflow_webserver_auth_backend: airflow.contrib.auth.backends.ldap_auth
```
2. Deploy Airflow using the role
3. Check the web UI

**Expected behavior:** Airflow web UI working.

**Actual behavior:** Airflow web UI not working.

**Reproduces how often:** Always

### Versions

Since 1.7.0 (first compatible with Airflow 1.10.0)
